### ISSUE TITLE
Dockerfile 

### ISSUE THREAD

**Issue by casperghst42** [git-developer/asset-upnp#1]
Hi,

It would be cool if you would share the Dockerfile so that people having a licensed version would be able to build an image with it.

Also you need to include 'curl' in your image, I'm getting:

sh: curl: not found
sh: curl: not found
sh: curl: not found
sh: curl: not found
sh: curl: not found
sh: curl: not found
sh: curl: not found

Cheers,
Casper

**Comment by git-developer** [comment]
Hi Casper, the Dockerfile is [here](https://github.com/git-developer/asset-upnp/blob/develop/image/Dockerfile). `curl` is not used in it, I wonder what it's needed for.

**Comment by casperghst42** [comment]
Hi,

Thanks, should have looked there.

I only know that the log shows that 'curl' is missing. Not sure it have any influence on functionality.

Thank you.
