### ISSUE TITLE
Free edition?

### ISSUE THREAD

**Issue by mwhdc** [git-developer/asset-upnp#2]
Hello, thanks for publishing this Dockerfile. I recently used it via Docker Hub to deploy a container. It pulled the latest release (R7+) of Asset which no longer offers a free level of usage. Then I deployed your tag R6.7 which I assume was the last release that runs indefinitely without a license. However, it still states "Functionality: Trial 30 Days Remaining" in the web UI. Do you know if R6.7 will revert to the free version after the trial period ends?

**Comment by git-developer** [comment]
Yes, it will. I'm running R6.7, too.

**Comment by mwhdc** [comment]
That's great to hear, thank you. The change of license model doesn't seem to be documented or discussed anywhere. Asset is the only UPnP server I have found that the Sonos app will recognize.
